<?php

namespace App\Traits;

use App\Traits\ApiTrait;

trait DimsReportsTrait
{
    use ApiTrait;

    public function apiBackordersandawaiting()
    {
        // $user = auth()->guard('central_api_user')->user();
        // $response = $this->httpRequest('post', 'general/getcustomers', [
        //     'userId' => $user->erp_user_id,
        //     'companyid' => $user->company_id,
        // ]);

        $response = [
            [
                "prodStatusType" => "",
                "productId" => "5536",
                "PastelCode" => "CB4Y-008",
                "Description" => "EVERYDAY TOMATOE PUREE 12x410g",
                "UnBookedStock" => "0",
                "Ordered" => "2.0",
                "originalQty" => "2.0",
                "DeliveryDate" => "2020-06-23",
                "OrderNo" => "PUR8872 - YORK STR",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1478545",
                "OrderId" => "380265",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "EA",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "9869",
                "PastelCode" => "500181",
                "Description" => "KOTEX MAXI WHITE NORM/W 16x10s",
                "UnBookedStock" => "0",
                "Ordered" => "2.0",
                "originalQty" => "1.0",
                "DeliveryDate" => "2020-06-23",
                "OrderNo" => "PUR8872 - YORK STR",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1478546",
                "OrderId" => "380265",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => null,
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "6510",
                "PastelCode" => "6063322",
                "Description" => "BLUE SEAL PET JELLY OP 12x50ml",
                "UnBookedStock" => "0",
                "Ordered" => "1.0",
                "originalQty" => "1.0",
                "DeliveryDate" => "2022-01-31",
                "OrderNo" => "",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1480085",
                "OrderId" => "384520",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "EA",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "6520",
                "PastelCode" => "6095224",
                "Description" => "BRUT DEO COLOGNE       6x120ml",
                "UnBookedStock" => "0",
                "Ordered" => "1.0",
                "originalQty" => "10.0",
                "DeliveryDate" => "2022-01-31",
                "OrderNo" => "",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1480089",
                "OrderId" => "384520",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "EA",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "1228",
                "PastelCode" => "009A",
                "Description" => "BULLBRAND WW SM MUTT  5x4x200g",
                "UnBookedStock" => "0",
                "Ordered" => "1.0",
                "originalQty" => "1.0",
                "DeliveryDate" => "2022-01-31",
                "OrderNo" => "",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1480086",
                "OrderId" => "384520",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "CASE",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "2199",
                "PastelCode" => "NET6",
                "Description" => "CERES 200ml MEDLY OF FRUIT x24",
                "UnBookedStock" => "0",
                "Ordered" => "1.0",
                "originalQty" => "1.0",
                "DeliveryDate" => "2022-01-31",
                "OrderNo" => "",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1480087",
                "OrderId" => "384520",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "EA",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "784",
                "PastelCode" => "GMB-7",
                "Description" => "COKE BUDDY 440 IRON BREW   x24",
                "UnBookedStock" => "0",
                "Ordered" => "1.0",
                "originalQty" => "125.0",
                "DeliveryDate" => "2022-01-31",
                "OrderNo" => "",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1480090",
                "OrderId" => "384520",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "EA",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "786",
                "PastelCode" => "GMB-9",
                "Description" => "COKE BUDDY 440 LEM/TWIST   x24",
                "UnBookedStock" => "0",
                "Ordered" => "1.0",
                "originalQty" => "1.0",
                "DeliveryDate" => "2022-01-31",
                "OrderNo" => "",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1480088",
                "OrderId" => "384520",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "EA",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ],
            [
                "prodStatusType" => "",
                "productId" => "60",
                "PastelCode" => "100X150-1",
                "Description" => "BAKERS EET SUM MOR C/C 12x200g",
                "UnBookedStock" => "0",
                "Ordered" => "1.0",
                "originalQty" => "1.0",
                "DeliveryDate" => "2023-04-12",
                "OrderNo" => ".",
                "Comment" => "",
                "DeliveryAddressID" => "0",
                "OrderDetailId" => "1480339",
                "OrderId" => "384681",
                "ID" => "awaiting",
                "Cost" => "108",
                "UnitSize" => "EA",
                "UnitWeight" => null,
                "SoldByWeight" => "0",
                "strBulkUnit" => null,
                "ProductMargin" => "14.99",
                "Tax" => "15.0",
                "StoreName" => "000001Customer"
            ]
        ];

        return $response;
    }
}
